version: 2

project_name: nexus

before:
  hooks:
    - go mod tidy

builds:
  - id: nexus
    main: ./cmd/tasklog
    binary: nexus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: krisk248
    name: nexus
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

brews:
  - name: nexus
    repository:
      owner: krisk248
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/krisk248/nexus"
    description: "A beautiful terminal-based task manager with Ultraviolet theme"
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/nexus", "--version"
    install: |
      bin.install "nexus"

nfpms:
  - id: default
    package_name: nexus
    vendor: krisk248
    homepage: "https://github.com/krisk248/nexus"
    maintainer: "krisk248"
    description: "A beautiful terminal-based task manager with Ultraviolet theme"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
